artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/rahul6796/datasets1/raw/main/conll2003.zip
  local_file_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FIEL: artifacts/data_validation/status.txt
  ALL_REQUIRED_FIELS: ['train', 'test', 'validation']


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/conll2003
  tokenizer_name: elastic/distilbert-base-uncased-finetuned-conll03-english


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/conll203_dataset
  model_ckpt: elastic/distilbert-base-uncased-finetuned-conll03-english





  